development:
  secret_key_base: 3342e9faedd8fe9ea360c0af568d00a46917923791c23e144d66849b272d2ff63e743f9bb209dab7d6e732bb5f919e46e3fe552b8919140805bb89c346e68876
  google_client_id: your_google_client_id
  google_client_secret: your_google_client_secret
  google_callback_url: 'http://localhost:3000/auth/google/callback'
  token_client_id: small_random_string
  token_secret:  large_random_string
test:
  google_client_id: test_google_client_id
  google_client_secret: test_google_client_secret
  google_callback_url: 'http://localhost:3000/auth/google/callback'
  token_client_id: test_client_id
  token_secret: test_client_secret
